services:
  test:
    image: local/ansible
    ports: 
      - 5601:5601
      - 9090:9090
    volumes: 
      - .:/etc/ansible      
    command: bash -c "ansible-playbook -vvvv /etc/ansible/monitoring_practice.yml && tail -f /dev/null"


