###############################
##    Monitoring practice    ##
###############################
---
- name: Monitoring server
  hosts: localhost
  become: yes
  
  roles:
    - prometheus
    - node_exporter
    - fluent_bit    
    - elasticsearch
