---

- name: Configure | td-agent-bit main conf
  template:
    src: td-agent-bit.conf.j2
    dest: /etc/td-agent-bit/td-agent-bit.conf
    mode: 0644

- name: Configure | td-agent-bit inputs
  template:
    src: 'inputs.conf.j2'
    dest: '/etc/td-agent-bit/inputs.conf'
    mode: 0644

- name: Configure | td-agent-bit outputs
  template:
    src: 'outputs.conf.j2'
    dest: '/etc/td-agent-bit/outputs.conf'
    mode: 0644
  notify: Restart fluentbit service

- name: Configure | td-agent-bit filters
  template:
    src: 'filters.conf.j2'
    dest: '/etc/td-agent-bit/filters.conf'
    mode: 0644
  when: fluentbit_filters is defined
  notify: Restart fluentbit service

- name: Configure | td-agent-bit custom parsers
  template:
    src: 'parsers.conf.j2'
    dest: '/etc/td-agent-bit/parsers.conf'
    mode: 0644
  when: fluentbit_custom_parsers is defined
  notify: Restart fluentbit service
